global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: bank_system_java
      scrape_interval: 5s
      metrics_path: /actuator/prometheus
      static_configs:
          - targets: ['host.docker.internal:8080']