global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: bank_system_kotlin
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
          - targets: ['host.docker.internal:8082']